name: Keep Alive

on:
  schedule:
    - cron: '0 */3 * * *'  # roda a cada 3 horas
  workflow_dispatch:         # permite rodar manualmente se necessário

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        run: curl -s -o /dev/null -w "%{http_code}" https://localiza-cx-teste.streamlit.app/
